### ISSUE TITLE
Remove escape sequences from log files

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#13]
Originally created on Wed, 22 Feb 2017 19:15:16 +0900

Logs, created by CI systems, are mostly .txt files that do not support any formatting by escape sequences, so these symbols should not be written to log files.

**Comment by iakoff** [comment]
Our project need to keep all ANSI symbols in log, because we use colorizing. Please, implement this feature only under special option key.

**Comment by i-keliukh** [comment]
@iakoff, could you, please, clarify, how exactly you use escape sequences in log files?
Do you download log files from CI system and print them to local terminal?

**Comment by iakoff** [comment]
I convert ansi to HTML using AHA toll(http://manpages.ubuntu.com/manpages/bionic/man1/aha.1.html).
Html files used as artifacts for review or as email report content.

**Comment by miltolstoy** [comment]
After collecting the clients' opinions, it was decided to close this issue.
Most of the clients don't care, and there is one active user of ANSI escape sequences in text logs.
