### ISSUE TITLE
Exclude unnecessary imports

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#131]
Originally created on Fri, 8 Dec 2017 01:00:55 +0900

Do not require Git/P4 installation and import when not using Git/P4 as VCS.

**Comment by k-dovgan** [comment]
Resolved on Wed, 12 Dec 2018 16:24:53 +0200

**Comment by i-keliukh** [comment]
The issue is resolved by commits 0528840fe8c4d464da047930f2f53e0fd244a94c, 6ac2c93a074b104ebbe681bda228e14794bc9e2d
