### ISSUE TITLE
Publish project on PyPI

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#236]
Add project to Python Package Index (https://pypi.org/) to be installable via pip.

**Comment by k-dovgan** [comment]
https://packaging.python.org/tutorials/packaging-projects/

**Comment by i-keliukh** [comment]
Don't forget to change documentation to remove things like this:
`sudo pip install .`

**Comment by k-dovgan** [comment]
https://test.pypi.org/project/Universum/

**Comment by k-dovgan** [comment]
https://www.codementor.io/arpitbhayani/host-your-python-package-using-github-on-pypi-du107t7ku

**Comment by axxie** [comment]
> https://test.pypi.org/project/Universum/

Just checked installation from test pypi. You have to install all dependencies first from normal pypi. I believe the test pypi just doesn't have them.

**Comment by i-keliukh** [comment]
> https://test.pypi.org/project/Universum/

The dependencies fail to install from the test pypi. After installing them from normal pypi, universum installed and worked ok.

**Comment by k-dovgan** [comment]
https://pypi.org/project/Universum/
