### ISSUE TITLE
Add a proper readme

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#237]
Update readme file to lead to project documentation instead of being a part of it

**Comment by k-dovgan** [comment]
1. Link to https://universum.readthedocs.io/
2. Instrunctions on Universum development
   * What to install and set up environment
   * How to run tests
   * Minimal architecture overview
3. Mandatory documenting of new features
4. Mandatory code review
5. CI
6. Links to community docs

**Comment by i-keliukh** [comment]
7. Add badges (e.g. Read the Docs)

**Comment by k-dovgan** [comment]
Mention that the project uses [semantic versioning](https://semver.org/)

**Comment by k-dovgan** [comment]
Badges: https://shields.io/#/

**Comment by k-dovgan** [comment]
Can be improved, but mostly meets the requirements.
