### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#238]
The logo should be in vector format to be easily scalable. We might use it as a big picture (e.g. in presentations), but we also have to put something to favicon, so we also need a pretty-looking small one.

As for the contents, it should represent the ideas of integration & connectivity, and also it'd be great if there was something like a star or stars (as it is called 'Universum' as in a reference to outer space).

**Comment by i-keliukh** [comment]
Proposed favicon:
![logo](https://user-images.githubusercontent.com/46344924/52182685-2a894780-2808-11e9-8b76-1d801b305cc2.png)

Proposed vector image:
[logo.zip](https://github.com/Samsung/Universum/files/2826001/logo.zip)
