### ISSUE TITLE
No default value in required argument checks

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#271]
## Description

Current argument checks (`if not getattr(self.settings, "user")`) fail if settings were not created via `argparser` and requested parameter is not present in settings at all.

## Steps to reproduce

1. Create settings manually
2. Miss some required option (e.g. "--launcher-config-path")
3. Call `create_component()` and pass created settings to it.

## Expected result

Any kind of "Required parameter not set" message in log (e.g. "Required option CONFIG_PATH (or '--launcher-config-path', or '-lcp') is missing.")

## Actual result

AttributeError: 'settings' object has no attribute <name>

Need to finish the following:
- [x] Commit  partial fixes + tests
- [x] Commit error message fixes
- [x] Commit subcommands fix
- [x] Commit test with del, None and empty string
- [x] Refactor Jenkins server
- [x] Fix argument checks in Jenkins server, add tests
- [x] Fix check_required_option in all code
- [ ] Add all other tests for argument checks

**Comment by i-keliukh** [comment]
The full list of incorrect checking of command line parameters:
```
Found Occurrences  (6 usages found)
    git_vcs.py  (1 usage found)
        247 if not getattr(self.settings, "user") or not getattr(self.settings, "email"):
    jenkins_server.py  (1 usage found)
        29 if getattr(self.settings, name) is None:
    launcher.py  (1 usage found)
        249 if getattr(self.settings, "config_path") is None:
    perforce_vcs.py  (1 usage found)
        330 if not getattr(self.settings, "client"):
    submit.py  (1 usage found)
        39 if getattr(self.settings, "commit_message") is None:
    teamcity_server.py  (1 usage found)
        31 if getattr(self.settings, name) is None:
```

**Comment by i-keliukh** [comment]
```
local_vcs.py  (1 usage found)
    34 if self.settings.source_dir is None:
```

**Comment by i-keliukh** [comment]
Need to finish the following:
- [ ] Commit  partial fixes + tests
- [ ] Commit error message fixes
- [ ] Commit subcommands fix
- [ ] Commit test with del, None and empty string
- [ ] Refactor Jenkins server
- [ ] Fix argument checks in Jenkins server, add tests
- [ ] Fix check_required_option in all code
- [ ] Add all other tests for argument checks
