### ISSUE TITLE
Wrong processing of execution interruption

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#272]
## Description

Current implementation of enforced program stop interception doesn't work, because all measures to prevent this are defined after execution the code that is interrupted.
To avoid this, `signal.signal` and `atexit` calls must be done before try-except block with `Uninterruptible`.

## Steps to reproduce

1. Launch Universum in any mode
2. Send SIGTERM to Universum process, or press ctrl+C before execution is finished

## Expected result

`finalize()` is executed anyway.

## Actual result

Program exits right away.

**Comment by i-keliukh** [comment]
@k-dovgan, please implement the fix.
