### ISSUE TITLE
The ${CODE_REPORT_FILE} variable is not being replaced

### ISSUE THREAD

**Issue by a-osipov-toxa** [Samsung/Universum#286]
## Description

There is no replacement of the pseudo-variable "${CODE_REPORT_FILE}" to the file name (generated by Universum). The "universum_pylint" module is used via specific way: through "bash -c ..." call. The `"code_report=True" `is added

Full config:
```
import os
from distutils.spawn import find_executable

from _universum.configuration_support import Variations, get_project_root

# Unittests and pylint check #
check = Variations([
    dict(name="Run",
         critical=True)
])
configs = check * Variations([
    dict(name=" python3.5 symlink create",
         command=["bash", "-c", "ln -s {} python3".format(find_executable('python3.5'))]),
    dict(name=" pylint3",
         code_report=True,
         command=["bash", "-c",
                  "export PATH=%s:$PATH; "
                  "universum_pylint --python-version 3 "
                  "--result-file ${CODE_REPORT_FILE} "
                  "--files *.py " % get_project_root()]),

])
```

## Steps to reproduce

 * Prepare the config file as mentioned above
 * Run the command: 
`universum --clean-build --vcs-type none -lo console --file-source-dir ./test_project/ --launcher-config-path ./universum_config.py`

## Expected result

All steps are executed without errors

## Actual result

The ${CODE_REPORT_FILE} variable is not changed to the real file name during config parsing by Universum. The bash interpreter try to execute `universum_pylint --result-file ${CODE_REPORT_FILE} --files *.py` command but the "CODE_REPORT_FILE" variable is empty. That is why the command is interpreted in `universum_pylint --result-file --files *.py` and error is occurred

Log:
```
5. Executing build steps
 |   5.1.  [  +  ] Run
 |      |   5.1.1.  [ 1/2 ] Run python3.5 symlink create
 |      |        |   $ /bin/bash -c ln -s /usr/bin/python3.5 python3
 |      |        |   
 |      |        └ [Success]
 |      |   
 |      |   5.1.2.  [ 2/2 ] Run pylint3
 |      |        |   $ /bin/bash -c export PATH=/home/test/temp:$PATH; universum_pylint --python-version 3 --result-file ${CODE_REPORT_FILE} --files *.py 
 |      |        |   stderr: usage: universum_pylint [-h] [--files FILE_LIST [FILE_LIST ...]]
 |      |        |   stderr:                         [--rcfile RCFILE] [--python-version {2,3}]
 |      |        |   stderr:                         [--result-file RESULT_FILE]
 |      |        |   stderr: universum_pylint: error: argument --result-file: expected one argument
 |      |        |   Error: Module sh got exit code 2
 |      |        |   
 |      |        └ [Failed]
 |      |   
 |      └ [Success]
 |   
 |   Critical step failed. All further configurations will be skipped
 └ [Success]
```

## Environment

 - OS: Ubuntu 14.04
 - Python version 2.7.6
 - Universum version 0.17.0

**Comment by a-osipov-toxa** [comment]
Additionally, I cannot use report collection with `artifacts=${CODE_REPORT_FILE},` option. 
**Even** when "pylint" step **is single** without nesting (multiplication)

```
[7. Collecting artifacts] 7.1. Collecting '${CODE_REPORT_FILE}'
[7.1. Collecting '${CODE_REPORT_FILE}'] ==> Processing '/home/test/temp/${CODE_REPORT_FILE}'
[7.1. Collecting '${CODE_REPORT_FILE}'] No artifacts found!
```

**Comment by k-dovgan** [comment]
> Additionally, I cannot use report collection with `artifacts=${CODE_REPORT_FILE},` option.

Unfortunately, this functionality is only to be added soon. See task #218

**Comment by a-osipov-toxa** [comment]
The following config failed with the same behavior 
```
configs = Configuration([Step(critical=True,)]) * Configuration([
    Step(name='PMD report',
         code_report=True,
         report_artifacts='${CODE_REPORT_FILE}',
         command=['bash', '-c', 'cp CI/tools/PMD/report.json ${CODE_REPORT_FILE}']),
])
```

with error log:
```
5.2.  [ 2/2 ] PMD report
$ /bin/bash -c 'cp CI/tools/PMD/report.json /home/tcagent03/buildAgent/work/cbbe15659b41d983/temp/code_report_results/PMD_report.json'
cp: cannot stat 'CI/tools/PMD/report.json': No such file or directory
Module sh got exit code 1
```

Please note that the same config without multiplier `Configuration([Step(critical=True,)])` will be successful.
