### ISSUE TITLE
Potential error in the analyzers/pylint.py

### ISSUE THREAD

**Issue by plazma123** [Samsung/Universum#314]
## Description

Potential error in the analyzers/pylint.py:
https://github.com/Samsung/Universum/blob/2485c91ba63b3e780711d9c1e6ceb4d3774e2e4e/analyzers/pylint.py#L56

If "pylint" return an empty line with "\n" control character it could be processed here:
https://github.com/Samsung/Universum/blob/2485c91ba63b3e780711d9c1e6ceb4d3774e2e4e/analyzers/pylint.py#L70

as not empty line and return an error:
https://github.com/Samsung/Universum/blob/2485c91ba63b3e780711d9c1e6ceb4d3774e2e4e/analyzers/pylint.py#L79

## Steps to reproduce

Create virtual environment and activate it. Run universum with config:

`/bin/bash -c source /home/work/venv/bin/activate && universum_pylint --python-version 3 --result-file code_report_results/Pylint3.5_check.json --files *.py`

## Expected result

Successfully checked

## Actual result
Failed, but without any pylint errors:

```
[]
Module sh got exit code 1
```

## Environment

 - Ubuntu 16.04.5
 - Python 3.5
 - Universum 0.16.02

```
python3.5 -m pylint --version
__main__.py 2.2.2
astroid 2.1.0
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]
```

**Comment by k-dovgan** [comment]
Under investigation, couldn't reproduce yet.

**Comment by k-dovgan** [comment]
Seems that Universum 0.17.0 doesn't have this problem, but I'm still not sure what exactly was causing it.

**Comment by i-keliukh** [comment]
Confirm, e43ca2f fixed the bug.
