### ISSUE TITLE
Filter steps which should be executed

### ISSUE THREAD

**Issue by i-savynikh** [Samsung/Universum#363]
**Problem.** Unable to choose steps which 'Universum' should execute. Alternative is a separate 'config' files usage, however it's not user-friendly enough.

**Supposed use-case.** 
A 'Universum config' contain a lot of steps related to build project for a different platforms and/or configurations. 
For example, 'config' contain next steps: 'Build Android', 'Build TEEgris', 'Build Tizen', 'Run Unit tests', 'Test Android'. It could be useful to run only **'Android'** steps.
```bash
universum [args] --filter "*Android*"
```
In this case only 'Build Android' and 'Test Android' steps should be executed.

Also, it could be useful to apply multiple filters:
```bash
universum [args] --filter "*Android*:*test*"
```
In this case the following steps will be executed: 'Build Android', 'Test Android', 'Run Unit tests'.

This feature will highly improve user experience for projects which use 'Universum' as build system wrapper.

**Comment by k-dovgan** [comment]
Can be implemented as a part of #43
