### ISSUE TITLE
Created CL is not cleaned on failed submit

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#388]
## Description
If submit fails, reconciled changes are stored in newly created CL; this behaviour interferes with automation.

### Steps to reproduce
1. Configure special p4 submit requirements, such as mandatory review or explicit CL description.
2. Use Universum to submit a CL not meeting those requirements.

### Expected result
Exception logged; local files left unchanged; created CL deleted; changes in VCS reverted

### Actual result
Exception logged; local files left unchanged; created CL left hanging with all changes added for VCS

**Comment by k-dovgan** [comment]
Here's the list of possible scenarios, leading to this error:
* requirements of special CL description format not fulfilled
* requirements of mandatory code review not fulfilled
* no 'write' rights for the target
* submitted files have been changed since CL creation (e.g. by another user)
* server-side problems (e.g. server application crashed)
* network problems (e.g. server temporarily inaccessible)

**Comment by i-keliukh** [comment]
Please create separate issue for tracking the implementation of test for handling of submit failure and copy the description of the scenarios there.

**Comment by k-dovgan** [comment]
See #396

**Comment by k-dovgan** [comment]
Fixed by #409
