### ISSUE TITLE
Wrong Step value response for the extra/custom key

### ISSUE THREAD

**Issue by a-osipov-toxa** [Samsung/Universum#764]
## Description

If you set the extra (_custom_) key value of the Step as a `False` you will get a `None` value if request it.

## Steps to reproduce

Define the config:
```
from universum.configuration_support import Step, Configuration as Conf

configs = Conf([Step('[Release] ', extra_key=False), ])

for i in configs.all():
    print(i.get('extra_key'))
    print(i)
```

## Expected result

Output must be:
```
False
{'name': '[Release] ', 'extra_key': False}
```

## Actual result

Output is:
```
None
{'name': '[Release] ', 'extra_key': False}
```

## Environment

 - OS: Ubuntu 16.04.5
 - Python version: 3.7
 - Universum version: 0.19.12

## Additional context

Probably you have to fix in this point:
https://github.com/Samsung/Universum/blob/70941fa225faa65e5a14e20c20477c9bf1af76c8/universum/configuration_support.py#L354

**Comment by i-keliukh** [comment]
Author is @o-andrieiev

**Comment by o-andrieiev** [comment]
yep, it seems the line https://github.com/Samsung/Universum/blob/70941fa225faa65e5a14e20c20477c9bf1af76c8/universum/configuration_support.py#L355

should read

> if result is not None:

should be an easy fix
