### ISSUE TITLE
Support `originalUriBaseIds` field for SARIF report

### ISSUE THREAD

**Issue by a-osipov-toxa** [Samsung/Universum#824]
## Description

The current implementation does not support the SARIF-formatted report files containing the `originalUriBaseIds` field. As a result, Universum does not transfer underline comments to the Swarm review

See the code: https://github.com/Samsung/Universum/blob/master/universum/modules/code_report_collector.py#L76

## Steps to reproduce

List the performed steps, for example:
 * Prepare the project code with the linter-warnings;
 * Prepare the Universum config with generation of SARIF formatted code report;
 * Configure Universum for the review report
 * Request the review
 * Check that the report was prepared and collected
 * Check the review comments from the Universum user

Additional info:
 * Command line: `python3.8 -m universum  --p4-force-clean --html-log universum_log.html --no-diff --report-to-review --report-build-start --report-build-success --build-only-latest`

 * Contents of configuration file 
```
from universum.configuration_support import Configuration, Step, get_project_root

MTH_ROOT_PATH = '/home/user/project'
target_linter_files = (f'{MTH_ROOT_PATH}/*.py {MTH_ROOT_PATH}/common/python/ '
                       f'{MTH_ROOT_PATH}/suites/ {MTH_ROOT_PATH}/stubs/')

flake8 = Configuration([
    Step(name=f'Flake8 {python_version} check',
            code_report=True,
            if_env_set='SKIP_FLAKE8 != true',
            report_artifacts='${CODE_REPORT_FILE}',
            command=['bash', '-c', f'python3.8 -m flake8 --config {ROOT_PATH}/.flake8 '
                                f'--filename={target_linter_files} '
                                '> ${CODE_REPORT_FILE}'),
])

# ============ Universum config preparation ==============
configs = flake8

if __name__ == '__main__':
    print(configs.dump())
```

## Expected result

All warnings/errors from the report file must be posted as an underline comments in review

## Actual result

There are no comments with warnings/errors from linter

## Environment

 - OS: Ubuntu 20.04
 - Python version 3.8
 - Universum version 0.19.17

## Additional context

Example of the report file (from flake8)
[Flake8_check.json](https://github.com/Samsung/Universum/files/13191054/Flake8_check.json)

**Comment by lyubomyrferents** [comment]
Hello,
I have a solution to this issue.
Please assign it to me.
